### PR TITLE
Change English province name in csv

### PR DESCRIPTION
**Pull request by izcream**

### CODE REVIEW

**Comment by uatthaphon** [comment]
Hi @izcream, Are you sure this commit is a corrected spelling?
This should be already corrected "Kamphaeng Phet", "Suphan Buri", So no need to updated it.

**Comment by izcream** [comment]
Sorry for distrub bro, I'm just do a challange for hacktoberfest 😄

**Comment by uatthaphon** [comment]
Ok Got it. No problem. :wink:

**Comment by uatthaphon** [comment]
The spelling already corrected, no need to change.

**Pull request closed without merging**
